version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: redacted
      POSTGRES_DB: redacted
  web:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:redacted@db:5432/redacted
    ports:
    - "9011:80"
    depends_on:
    - db
  