version: '3'
services:
  nginx:
    image: nginx:1.23-alpine
    ports:
    - "9005:80"
    volumes:
    - "./src/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    networks:
      default:
        aliases:
        - "internal.ctf99.cs.ui.ac.id"
    depends_on:
    - web-public
    - web-private
  web-public:
    build: .
    volumes:
    - "./src/web-public:/var/www/html"
  web-private:
    build: .
    volumes:
    - "./src/web-private:/var/www/html"